"""
NDF path translation between Compat (OG Ubisoft) and Updated (Steam Remaster) game versions.

The Updated game consolidates all DAT files into PC/190852/ and reorganised the
internal launchermap chain that encodes the game's full map list as nested folder
paths inside ZZ_GladPatchableWin.dat.

The 15 "core" NDF files (everything.cpp, everythinggdconstanteoriginal.cpp, etc.)
are path-identical between versions — no translation needed for gameplay mods.

Only the launchermap subtree differs. The chain diverges at chqlmapscriptingedge/:
  Compat: ...edge/chqlmapscriptinggam_ostfriesland/...
  Updated: ...edge/chqlmapscriptingflat/afrique/... (10 new maps) .../chqlmapgam_ostfriesland/...

This module provides one-way translation: Compat NDF path → Updated NDF path.
"""

# ── Terminal chain prefixes ────────────────────────────────────────────────────
# Derived from the path to chqlmapinfo.cpp.gladndfbin (the single terminal node)
# in each version's ZZ_GladPatchableWin.dat.  Everything after this prefix is
# the same between versions (chqlmapisc/... sub-tree), modulo the inner
# SCENARIO substitutions below.

_COMPAT_CHAIN_PREFIX = (
    "genglad/patchable/clustergfx/everythinggdconstantevisibilityia/launchermap"
    "/alpha/chqlmapscriptingbattleofthebulge/chqlmapeta/chqlmapchess"
    "/chqlmapscriptingmate/chqlmapscriptingompassrose"
    "/chqlmapscriptingdiplomatietriangulaire/chqlmapscripting_colly"
    "/chqlmapscriptingedge"
    "/chqlmapscriptinggam_ostfriesland/chqlmapma/chqlmaphurtgen/chqlmapkorsun"
    "/chqlmaprakdeschevaliers/chqlmapursk43_ladder/chqlmapscriptingm01_leipzig"
    "/chqlmap2_tunisie/chqlmapscripting_chapter3_italie"
    "/chqlmapscripting_chapter4_cotentin/chqlmapscripting_chapter5_hollande"
    "/chqlmapscripting_chapter6_ardennes/chqlmapscripting_chapter7_allemagne"
    "/chqlmapscripting_chapter8_allemagne/chqlmapscripting_chapter2ireille"
    "/chqlmapscriptingrobert/chqlmapseize/chqlmapquare/chqlmapupercrossroads4"
    "/chqlmapscriptingwamps/chqlmapscriptingtwoislands/chqlmapscriptingvalley/"
)

_UPDATED_CHAIN_PREFIX = (
    "genglad/patchable/clustergfx/everythinggdconstantevisibilityia/launchermap"
    "/alpha/chqlmapscriptingbattleofthebulge/chqlmapeta/chqlmapchess"
    "/chqlmapscriptingmate/chqlmapscriptingompassrose"
    "/chqlmapscriptingdiplomatietriangulaire/chqlmapscripting_colly"
    "/chqlmapscriptingedge"
    "/chqlmapscriptingflat/afrique/chqlmapllemagne/chqlmaprdennes/chqlmapbase"
    "/chqlmapjap/chqlmapfrance/chqlmaphollande/chqlmapia/chqlmaptalie"
    "/chqlmaplight/chqlmapgam_ostfriesland/chqlmapma/chqlmaphurtgen/chqlmapkorsun"
    "/chqlmaprakdeschevaliers/chqlmapursk43_ladder/chqlmapscripting_cham01_leipzig"
    "/chqlmap2_tunisie/chqlmapscripting_chapter3_italie"
    "/chqlmapscripting_chapter_demo_final/chqlmap4_cotentin"
    "/chqlmapscripting_chapter5_hollande/chqlmapscripting_chapter6_ardennes"
    "/chqlmapscripting_chapter7_allemagne/chqlmapscripting_chapter8_allemagne"
    "/chqlmapscripting_chapter2ireille/chqlmapscriptingrobert/chqlmapseize"
    "/chqlmapquare/chqlmapupercrossroads4/chqlmapscripting_wamps"
    "/chqlmapscriptingtestia/chqlmapwoislands/chqlmapscriptingvalley/"
)

# ── chqlmapinfo.cpp.gladndfbin instance index tables ─────────────────────────
# Maps OG (compat/99) global instance positions to Updated positions.
# Derived by name-matching TMapLoadInfo.Name and TUIResourceTexture.FileName
# across both NDF versions.  Only entries that *differ* are listed; unmapped
# indices are returned as-is.

_ML_OG_TO_UPD = {
    # Generated by name-matching TMapLoadInfo.Name across compat/public mapinfo.cpp.gladndfbin.
    # Compat-only maps (no public match): idx 0 (_Outgame), 532 (Tech: Flat Orbit),
    #   537 (Tech: Flat TestRDF), 556 (Tech: Generation rapport de force).
    5: 0, 10: 5, 17: 12, 24: 19, 29: 24, 34: 29, 39: 34, 44: 39, 51: 46, 56: 51, 61: 56,
    66: 61, 74: 68, 81: 75, 86: 80, 91: 85, 98: 92, 103: 97, 108: 102, 115: 109, 120: 114,
    125: 119, 132: 126, 137: 131, 142: 136, 149: 143, 154: 148, 159: 153, 166: 160, 173: 167,
    181: 174, 188: 181, 195: 188, 202: 195, 209: 202, 216: 209, 223: 216, 230: 223, 237: 230,
    244: 237, 251: 244, 259: 251, 266: 258, 273: 265, 280: 272, 287: 279, 294: 286, 301: 293,
    308: 300, 315: 307, 322: 314, 329: 321, 336: 328, 343: 335, 349: 341, 355: 347, 363: 354,
    370: 361, 375: 366, 380: 371, 386: 377, 393: 384, 399: 390, 406: 397, 412: 403, 418: 409,
    424: 415, 430: 421, 438: 428, 445: 434, 453: 441, 460: 447, 468: 454, 476: 461, 483: 468,
    490: 475, 497: 482, 504: 489, 511: 496, 518: 503, 525: 510, 544: 517, 551: 524, 563: 529,
    568: 534, 575: 541,
}

_TX_OG_TO_UPD = {
    # Generated by name-matching TUIResourceTexture.FileName across compat/public mapinfo.cpp.gladndfbin.
    # Compat-only textures (no public match): idx 538-539 (flat/TestRDF),
    #   557-558 (flat/GenRapportDeForce).
    11: 6, 12: 7, 18: 13, 19: 14, 45: 40, 46: 41, 67: 62, 68: 63, 75: 69, 76: 70, 92: 86,
    93: 87, 109: 103, 110: 104, 126: 120, 127: 121, 143: 137, 144: 138, 160: 154, 161: 155,
    167: 161, 168: 162, 174: 168, 175: 169, 182: 175, 183: 176, 189: 182, 190: 183, 196: 189,
    197: 190, 203: 196, 204: 197, 210: 203, 211: 204, 217: 210, 218: 211, 224: 217, 225: 218,
    231: 224, 232: 225, 238: 231, 239: 232, 245: 238, 246: 239, 252: 245, 253: 246, 260: 252,
    261: 253, 267: 259, 268: 260, 274: 266, 275: 267, 281: 273, 282: 274, 288: 280, 289: 281,
    295: 287, 296: 288, 302: 294, 303: 295, 309: 301, 310: 302, 316: 308, 317: 309, 323: 315,
    324: 316, 330: 322, 331: 323, 337: 329, 338: 330, 344: 336, 350: 342, 356: 348, 357: 349,
    364: 355, 365: 356, 381: 372, 387: 378, 388: 379, 394: 385, 400: 391, 401: 392, 407: 398,
    413: 404, 419: 410, 425: 416, 431: 422, 432: 423, 439: 429, 446: 435, 447: 436, 454: 442,
    461: 448, 462: 449, 469: 455, 470: 456, 477: 462, 478: 463, 484: 469, 485: 470, 491: 476,
    492: 477, 498: 483, 499: 484, 505: 490, 506: 491, 512: 497, 513: 498, 519: 504, 520: 505,
    526: 511, 527: 512, 545: 518, 546: 519, 569: 535, 570: 536, 576: 542, 577: 543,
}


# ── everything.cpp.gladndfbin instance-index remapping ───────────────────────
# Public remaster differs from compat in the 46000–50000 region: Uplay/touch-
# screen classes were removed (46705, 46706, 46748) and public inserted ~16
# new instances before position 46616, creating a non-uniform offset landscape.
# Below 46616 the layout is identical (offset 0).  Above ~50200 a uniform -17
# offset applies.  In between, per-instance mappings are needed.
#
# Derived by content-matching stable (non-ObjRef) property values between the
# compat PC/99 ZZ_GladPatchableWin.dat and public PC/190852 version.
# None = instance removed from public (Uplay-specific).
_COMPAT_EVERYTHING_IDX_SPECIFIC: dict = {
    46616: 46632,  # TInterfaceInGameMenusResource (+16)
    46664: 46680,  # TLoadableQuadTextureAnimatedBladeAndResizeViewPort (+16)
    46752: 46759,  # TUIResourceTexture (+7, transition zone)
    46821: 46824,  # TUnitDescriptorResource (+3)
    46822: 46825,  # TUniteBehaviourDescriptor (+3)
    46823: 46826,  # TViewVariantConfiguration (+3)
    46825: 46828,  # TViewVariantConfiguration (+3)
    46827: 46830,  # TViewVariantConfiguration (+3)
    46830: 46833,  # TActionCall (+3)
    46835: 46838,  # TActionCall (+3)
    46836: 46839,  # TActionCall (+3)
    46837: 46840,  # TActionCall (+3)
    46838: 46841,  # TActionCall (+3)
    46893: 46896,  # TActionCall (+3, class count same, regional offset)
    47275: 47278,  # TGfxDescriptorModeleWithAnimation 'Gfx_Junkers_87_Rudel' (+3)
    47602: 47605,  # TGfxDescriptorModeleWithAnimation (+3)
    47783: 47786,  # TGfxDescriptorModeleWithAnimation 'GfxIconeSignatureRadarAVION' (+3)
    47785: None,   # TGfxDescriptorModeleWithAnimation 'GfxIconeSignatureRadarAVIONUplay' — removed (Uplay)
    48850: 48851,  # TPawnDrawer (+1)
    48851: 48852,  # TPawnDrawer (+1)
    48859: 48860,  # TPawnSocleMatrix (+1)
    48860: 48861,  # TPawnSocleMatrix (+1)
}

# Indices >= this threshold get a uniform -17 offset (net removals above 50000).
# All compat rmod _index values in 48861–50199 range are unverified (none used
# in current rmods); if needed, add explicit entries to _COMPAT_EVERYTHING_IDX_SPECIFIC.
_EVERYTHING_CPP_OFFSET_THRESHOLD = 48888
_EVERYTHING_CPP_OFFSET = -17


# ── old-public (v23409545) → new-public (v23660935) everything.cpp shift ──────
# The v23660935 game update removed exactly one class from everything.cpp,
# TIntuifaceSelectionHandlerInGame (old-public class idx 220), and its single
# instance (old-public global idx 46753).  Every other class/instance keeps its
# identity, but its NUMERIC index shifts -1 if it sat above the removed slot.
# Verified by deriving the full old->new identity map from both NDFs
# (archive/ai_unit_tests/claude/migrate_rmods_to_new_public.py).
#
# The compat translation tables above (_COMPAT_*, _GLOBALS_*, mapinfo) were all
# derived against OLD-public, so the compat->public result is post-composed with
# this shift to land on NEW-public.  globals.cpp / mapinfo.cpp layouts did NOT
# change in this update (values only), so only everything.cpp needs this layer.
_NEWPUB_EVERYTHING_INST_REMOVED = 46753
_NEWPUB_EVERYTHING_CLS_REMOVED = 220


def _oldpub_to_newpub_everything_inst(i):
    """Shift an OLD-public everything.cpp instance index to NEW-public.
    Returns None if it referenced the one removed instance (caller skips)."""
    if i is None or i == _NEWPUB_EVERYTHING_INST_REMOVED:
        return None
    return i - 1 if i > _NEWPUB_EVERYTHING_INST_REMOVED else i


def _oldpub_to_newpub_everything_cls(c):
    """Shift an OLD-public everything.cpp class index to NEW-public.
    Returns None if it referenced the one removed class (caller keeps old)."""
    if c is None or c == _NEWPUB_EVERYTHING_CLS_REMOVED:
        return None
    return c - 1 if c > _NEWPUB_EVERYTHING_CLS_REMOVED else c


# ── globals.cpp.gladndfbin instance-index remapping ──────────────────────────
# globals.cpp has a completely different layout in public vs compat.
# TMultiMapInfo instances at compat 251-257 and TMultiPackManager at 258
# map to entirely different positions in public (offsets range from -106 to -122).
# Derived by matching TrackingId property values across compat and public.
_GLOBALS_CPP_IDX_REMAP: dict = {
    251: 129,  # TMultiMapInfo tid='MP01'
    252: 132,  # TMultiMapInfo tid='MP03'
    253: 136,  # TMultiMapInfo tid='MP10'
    254: 140,  # TMultiMapInfo tid='MP11'
    255: 143,  # TMultiMapInfo tid='MP15'
    256: 146,  # TMultiMapInfo tid='MP16'
    257: 151,  # TMultiMapInfo tid='MP23'
    258: 250,  # TMultiPackManager
}


# ── everything.cpp.gladndfbin class-index translation ─────────────────────────
# The CLAS table in everything.cpp differs between compat and public:
#   - TTFSCommand_AutomatedControllerSymbol inserted at public index 189 (not in compat)
#   - TInterfaceInGamePopUpUPlayManager (compat 206) removed from public
#   - TInterfaceInGamePopUpUPlayResource (compat 207) removed from public
#   - TTouchScreenSelectionHandlerInGame (compat 222) removed from public
# Net result: 197 compat class indices map to different public class indices.
# ObjRef values in rmod `set` fields store compat class indices; these must be
# translated when generating public .rmod files.
# Classes 0-188 are identical in both versions (not listed here).
# Compat indices 206, 207, 222 have no public equivalent (classes were removed).

_COMPAT_CLS_TO_PUBLIC = {
    # diff=+1: compat 189-205 (push right by TTFSCommand insertion at public 189)
    189: 190, 190: 191, 191: 192, 192: 193, 193: 194, 194: 195, 195: 196,
    196: 197, 197: 198, 198: 199, 199: 200, 200: 201, 201: 202, 202: 203,
    203: 204, 204: 205, 205: 206,
    # diff=-1: compat 208-221 (net: +1 TTFSCommand, -2 Uplay removals)
    208: 207, 209: 208, 210: 209, 211: 210, 212: 211, 213: 212, 214: 213,
    215: 214, 216: 215, 217: 216, 218: 217, 219: 218, 220: 219, 221: 220,
    # diff=-2: compat 223-388 (net: +1 TTFSCommand, -3 class removals)
    223: 221, 224: 222, 225: 223, 226: 224, 227: 225, 228: 226, 229: 227,
    230: 228, 231: 229, 232: 230, 233: 231, 234: 232, 235: 233, 236: 234,
    237: 235, 238: 236, 239: 237, 240: 238, 241: 239, 242: 240, 243: 241,
    244: 242, 245: 243, 246: 244, 247: 245, 248: 246, 249: 247, 250: 248,
    251: 249, 252: 250, 253: 251, 254: 252, 255: 253, 256: 254, 257: 255,
    258: 256, 259: 257, 260: 258, 261: 259, 262: 260, 263: 261, 264: 262,
    265: 263, 266: 264, 267: 265, 268: 266, 269: 267, 270: 268, 271: 269,
    272: 270, 273: 271, 274: 272, 275: 273, 276: 274, 277: 275, 278: 276,
    279: 277, 280: 278, 281: 279, 282: 280, 283: 281, 284: 282, 285: 283,
    286: 284, 287: 285, 288: 286, 289: 287, 290: 288, 291: 289, 292: 290,
    293: 291, 294: 292, 295: 293, 296: 294, 297: 295, 298: 296, 299: 297,
    300: 298, 301: 299, 302: 300, 303: 301, 304: 302, 305: 303, 306: 304,
    307: 305, 308: 306, 309: 307, 310: 308, 311: 309, 312: 310, 313: 311,
    314: 312, 315: 313, 316: 314, 317: 315, 318: 316, 319: 317, 320: 318,
    321: 319, 322: 320, 323: 321, 324: 322, 325: 323, 326: 324, 327: 325,
    328: 326, 329: 327, 330: 328, 331: 329, 332: 330, 333: 331, 334: 332,
    335: 333, 336: 334, 337: 335, 338: 336, 339: 337, 340: 338, 341: 339,
    342: 340, 343: 341, 344: 342, 345: 343, 346: 344, 347: 345, 348: 346,
    349: 347, 350: 348, 351: 349, 352: 350, 353: 351, 354: 352, 355: 353,
    356: 354, 357: 355, 358: 356, 359: 357, 360: 358, 361: 359, 362: 360,
    363: 361, 364: 362, 365: 363, 366: 364, 367: 365, 368: 366, 369: 367,
    370: 368, 371: 369, 372: 370, 373: 371, 374: 372, 375: 373, 376: 374,
    377: 375, 378: 376, 379: 377, 380: 378, 381: 379, 382: 380, 383: 381,
    384: 382, 385: 383, 386: 384, 387: 385, 388: 386,
}


# ── DataMap_Win.dat internal path substitutions ───────────────────────────────
# Applied (in order) to translate OG (compat) DataMap chain paths to Updated.
# Longer/earlier substrings first to avoid partial matches.

_DATAMAP_SUBS = [
    # Outer chain prefix: new maps between edge and gam_ostfriesland inserted
    (
        "elalameinzonebluff/leveldesign_gam_ostfriesland/",
        "elalameinzonebluff/leveldesign_flat/afrique/llemagne/rdennes/base"
        "/jap/france/hollande/ia/talie/light/zonebluff/leveldesigngam_ostfriesland/",
    ),
    # chapter_demo_final slot inserted before chapter4_cotentin
    (
        "leveldesign_chapter4_cotentin/",
        "leveldesign_chapter_demo_final/4_cotentin/",
    ),
    # testia inserted before woislands; twoislands → woislands rename
    (
        "leveldesigntwoislands/",
        "leveldesigntestia/woislands/",
    ),
    # Top-level outer prefix change
    (
        "datasmap/bchessdgamkm0stest/",
        "datasmap/bchessdgamkm03_italiesttest/",
    ),
]


# ── Inner scenario-subtree substitutions ──────────────────────────────────────
# Applied (in order) to the suffix AFTER the outer chain prefix has been swapped.
# The chqlmapisc/...scenario/... sub-tree encodes the same map list a second time
# using truncated names — it also changed in the same way as the outer chain.
# Longer / more-specific strings are listed first to avoid partial matches.

_INNER_SUBS = [
    # New maps inserted between edge and gam_ostfriesland in the scenario sub-chain
    (
        "edge/scenario/_challenge/gam_ostfriesland/scenario_ostfriesland/",
        "edge/scenario/_challenge/flat/afrique/scenario/llemagne/scenario/rdennes"
        "/scenario/base/scenario/jap/scenario/france/scenario/hollande/scenario/ia"
        "/scenarioplayable/talie/scenario/light/scenario/gam_ostfriesland"
        "/scenario_ostfriesland/",
    ),
    # challenge_mode_fast slot inserted before m01_leipzig
    (
        "challenge_3945/m01_leipzig/",
        "challenge_3945/nge_mode_fast/m01_leipzig/",
    ),
    # demo_final slot inserted before chapter3_italie; testauto inserted before it
    (
        "scenario_chapter1/2/3/4/3_italie/",
        "scenario_chapter1/2/3/4/testauto/3_italie/",
    ),
    (
        "scenario_chapter1/2/3/4/4_cotentin/",
        "scenario_chapter1/2/3/4/_demo_final/scenario4_cotentin/",
    ),
    # testia inserted before wamps
    (
        "scenario/_challenge_2/wamps/",
        "scenario/_challenge_2/testia/wamps/",
    ),
    # testia inserted before woislands; twoislands → woislands rename
    (
        "scenario/_challengeorbraves/twoislands/",
        "scenario/_challengeorbraves/testia/scenario/woislands/",
    ),
]


# ── ObjRef class translation helper ──────────────────────────────────────────

def translate_everything_cpp_set(value):
    """Translate ObjRef class indices in an everything.cpp set field value.

    Public wrapper for use in external tools (e.g. verify_rmod_translation).
    """
    return _translate_objref_classes(value)


def _compat_cls_to_public(compat_cls):
    """Translate a compat everything.cpp class index to the NEW-public class index.

    compat -> OLD-public (_COMPAT_CLS_TO_PUBLIC; identity for 0-188) then
    OLD-public -> NEW-public (-1 above the removed class 220).  Falls back to the
    OLD-public value if the v23660935 shift maps it to the one removed class
    (mirrors the lenient inst handling — the change is left for apply-time to
    skip rather than corrupting the value here)."""
    oldpub = _COMPAT_CLS_TO_PUBLIC.get(compat_cls, compat_cls)
    shifted = _oldpub_to_newpub_everything_cls(oldpub)
    return oldpub if shifted is None else shifted


def _translate_objref_classes(value):
    """Recursively translate ObjRef class/inst indices in a set field value.

    Handles three ObjRef forms:
    - Raw {"inst": N, "class": C}: translates both inst (>= 48888) and class (>= 189)
    - local_id {"local_id": "inst_N", "class": C}: translates class only
      (inst is resolved at apply time via create_map, but class must be pre-translated)
    - stable_ref {"stable_ref": ..., "class": C}: left unchanged
      (class is overridden at apply time from the live NDF instance)
    """
    if isinstance(value, dict):
        if "inst" in value and "class" in value:
            new_cls  = _compat_cls_to_public(value["class"])
            translated = translate_everything_cpp_index(value["inst"])
            new_inst = value["inst"] if translated is None else translated
            if new_cls == value["class"] and new_inst == value["inst"]:
                return value
            return {"inst": new_inst, "class": new_cls}
        if "local_id" in value and "class" in value:
            new_cls = _compat_cls_to_public(value["class"])
            if new_cls == value["class"]:
                return value
            return {**value, "class": new_cls}
        return {k: _translate_objref_classes(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_translate_objref_classes(item) for item in value]
    return value


# ── Public API ────────────────────────────────────────────────────────────────

def is_map_chain_path(ndf_path: str) -> bool:
    """Return True if this NDF path is inside the launchermap chain (version-specific)."""
    p = ndf_path.replace("\\", "/").lower()
    return "/launchermap/" in p


def translate_ndf_path(ndf_path: str) -> str:
    """
    Translate a Compat NDF path to its Updated equivalent.

    Core NDF files (no launchermap component) are returned unchanged.
    Paths that already use the Updated chain prefix (pre-converted rmods) are
    returned as-is.
    Paths that start with the known Compat terminal chain prefix are translated.
    Paths at intermediate chain depths (not yet used by any mod) are returned
    unchanged with a warning printed; add support as mods require it.
    """
    p = ndf_path.replace("\\", "/")
    p_lower = p.lower()

    if not is_map_chain_path(p_lower):
        return ndf_path  # core file — no translation needed

    # Already translated (e.g. pre-converted public rmod) — return as-is
    if p_lower.startswith(_UPDATED_CHAIN_PREFIX.lower()):
        return p

    compat_lower = _COMPAT_CHAIN_PREFIX.lower()
    if p_lower.startswith(compat_lower):
        suffix = p[len(_COMPAT_CHAIN_PREFIX):]
        for old, new in _INNER_SUBS:
            suffix = suffix.replace(old, new)
        return _UPDATED_CHAIN_PREFIX + suffix

    # Intermediate-depth compat path — not yet mapped
    print(f"[path_map] WARNING: no translation for intermediate chain path: {ndf_path[:80]}...")
    return ndf_path


def is_chqlmapinfo_ndf(ndf_path: str) -> bool:
    """Return True if the NDF path targets chqlmapinfo.cpp.gladndfbin."""
    return "chqlmapinfo.cpp.gladndfbin" in ndf_path.replace("\\", "/").lower()


def is_mapinfo_cpp_ndf(ndf_path: str) -> bool:
    """Return True if the NDF path targets mapinfo.cpp.gladndfbin."""
    p = ndf_path.replace("\\", "/").lower()
    return p.endswith("mapinfo.cpp.gladndfbin")


def is_everything_cpp_ndf(ndf_path: str) -> bool:
    """Return True if the NDF path targets everything.cpp.gladndfbin (not debuginfo)."""
    p = ndf_path.replace("\\", "/").lower()
    return (p.endswith("everything.cpp.gladndfbin")
            and "debuginfo" not in p)


def is_globals_cpp_ndf(ndf_path: str) -> bool:
    """Return True if the NDF path targets globals.cpp.gladndfbin."""
    return ndf_path.replace("\\", "/").lower().endswith("globals.cpp.gladndfbin")


def translate_index(table: str, og_index: int) -> int:
    """Translate a chqlmapinfo global instance index from OG to Updated.

    Returns the Updated index, or og_index unchanged if not in the lookup table.
    """
    t = table.lower()
    if t == "tmaploadinfo":
        return _ML_OG_TO_UPD.get(og_index, og_index)
    if t == "tuiresourcetexture":
        return _TX_OG_TO_UPD.get(og_index, og_index)
    return og_index


def translate_everything_cpp_index(og_index: int):
    """Translate a compat everything.cpp global instance index to the (NEW-)public index.

    Two stages: compat -> OLD-public (the verified _COMPAT_* tables), then
    OLD-public -> NEW-public (the v23660935 -1-above-46753 shift).

    Returns the translated int index, or None if the instance has no NEW-public
    equivalent (removed in the remaster, e.g. Uplay-specific, or removed by the
    v23660935 update).  Callers must check for None and skip such changes.
    """
    if og_index in _COMPAT_EVERYTHING_IDX_SPECIFIC:
        oldpub = _COMPAT_EVERYTHING_IDX_SPECIFIC[og_index]
    elif og_index >= _EVERYTHING_CPP_OFFSET_THRESHOLD:
        oldpub = og_index + _EVERYTHING_CPP_OFFSET
    else:
        oldpub = og_index
    return _oldpub_to_newpub_everything_inst(oldpub)


def translate_ia_common_path(path: str) -> str:
    """Translate a compat IA_Common.dat internal path to the public format.

    The prefix changed from genpython/100000/ (compat PC/1360/) to
    genpython/10000/ (public PC/190852/).  Map names are unchanged.
    """
    p = path.replace("\\", "/")
    if p.lower().startswith("genpython/100000/"):
        return "genpython/10000/" + p[len("genpython/100000/"):]
    return p


def translate_loc_path(path: str) -> str:
    """Translate a ZZ_Win.dat localization (.dic) internal path from compat to public.

    The per-language folder changed: compat `…/localisation/generated/<lang>/…` becomes public
    `…/localisation/translations/<lang>/…`.  The `dev/` default-language path is identical in both
    builds and is left unchanged."""
    p = path.replace("\\", "/")
    marker = "/localisation/generated/"
    idx = p.lower().find(marker)
    if idx >= 0:
        return p[:idx] + "/localisation/translations/" + p[idx + len(marker):]
    return p


def translate_datamap_path(path: str) -> str:
    """Translate a DataMap_Win.dat internal path from Compat to Updated format."""
    p = path.replace("\\", "/")
    p_lower = p.lower()
    for old, new in _DATAMAP_SUBS:
        idx = p_lower.find(old)
        if idx >= 0:
            p = p[:idx] + new + p[idx + len(old):]
            p_lower = p.lower()
    return p


def translate_rmod_data(rmod_data: dict) -> dict:
    """
    Return a deep copy of rmod_data with all paths and indices translated
    from compat (PC/99, PC/1360) to public (PC/190852) format.

    Translations applied:
    - dat paths: PC/99/ or PC/1360/ → PC/190852/
    - ndf paths: launchermap chain prefix substitution (core files unchanged)
    - everything.cpp _index/ObjRef: compat→old-public tables, then the v23660935
      -1-above-46753 (inst) / -1-above-220 (class) shift to NEW-public
    - mapinfo.cpp _index: TMapLoadInfo / TUIResourceTexture index tables applied
    - IA_Common.dat file paths: genpython/100000/ → genpython/10000/
    """
    import copy
    out = copy.deepcopy(rmod_data)
    for patch in out.get("patches", []):
        # ── DAT path ──
        dat = patch.get("dat", "")
        if dat:
            filename = dat.replace("\\", "/").split("/")[-1]
            patch["dat"] = f"PC/190852/{filename}"

        # ── NDF path ──
        ndf = patch.get("ndf", "")
        if ndf:
            patch["ndf"] = translate_ndf_path(ndf)
            ndf = patch["ndf"]

        # ── Per-change translations ──
        is_everything = is_everything_cpp_ndf(ndf)
        is_mapinfo    = is_mapinfo_cpp_ndf(ndf)
        is_globals    = is_globals_cpp_ndf(ndf)
        kept_changes = []
        for change in patch.get("changes", []):
            match = change.get("match", {})
            skip = False

            # _index translation
            if "_index" in match:
                og_idx = int(match["_index"])
                new_idx = og_idx
                if is_everything:
                    new_idx = translate_everything_cpp_index(og_idx)
                    if new_idx is None:
                        # Target instance removed from public (e.g. Uplay-specific)
                        skip = True
                    elif new_idx != og_idx:
                        match["_index"] = str(new_idx)
                elif is_mapinfo:
                    new_idx = translate_index(change.get("table", ""), og_idx)
                    if new_idx != og_idx:
                        match["_index"] = str(new_idx)
                elif is_globals:
                    new_idx = _GLOBALS_CPP_IDX_REMAP.get(og_idx, og_idx)
                    if new_idx != og_idx:
                        match["_index"] = str(new_idx)

            if skip:
                continue

            # ObjRef class index translation in set values (everything.cpp only)
            if is_everything and change.get("set"):
                change["set"] = _translate_objref_classes(change["set"])

            # Strip Uplay-only properties that don't exist in public
            if change.get("set"):
                tbl = change.get("table", "")
                s = change["set"]
                if is_everything and tbl == "TPawnSocleList" and "SocleMeshListUplay" in s:
                    s = {k: v for k, v in s.items() if k != "SocleMeshListUplay"}
                    change["set"] = s
                if is_globals and tbl == "TMultiMapInfo" and "NotDispoInBattle" in s:
                    s = {k: v for k, v in s.items() if k != "NotDispoInBattle"}
                    change["set"] = s

            kept_changes.append(change)
        patch["changes"] = kept_changes

    # ── file_patches: DAT paths + IA_Common / DataMap internal paths ──
    for fg in out.get("file_patches", []):
        dat = fg.get("dat", "")
        if dat:
            filename = dat.replace("\\", "/").split("/")[-1]
            fg["dat"] = f"PC/190852/{filename}"
            fname_lower = filename.lower()
            is_ia = fname_lower == "ia_common.dat"
            is_datamap = "datamap" in fname_lower
        else:
            is_ia = False
            is_datamap = False

        if is_ia:
            for fp in fg.get("files", []):
                p = fp.get("path", "")
                if p:
                    fp["path"] = translate_ia_common_path(p)

        if is_datamap:
            for fp in fg.get("files", []):
                p = fp.get("path", "")
                if p:
                    fp["path"] = translate_datamap_path(p)

    # ── loc_patches: DAT path + .dic path (compat 'generated/<lang>' → public 'translations/<lang>') ──
    for lg in out.get("loc_patches", []):
        dat = lg.get("dat", "")
        if dat:
            filename = dat.replace("\\", "/").split("/")[-1]
            lg["dat"] = f"PC/190852/{filename}"
        dic = lg.get("dic", "")
        if dic:
            lg["dic"] = translate_loc_path(dic)

    # ── sdb_patches: DAT path + datasmap internal path (mapinfo.win) ──
    for sg in out.get("sdb_patches", []):
        dat = sg.get("dat", "")
        if dat:
            filename = dat.replace("\\", "/").split("/")[-1]
            sg["dat"] = f"PC/190852/{filename}"
        win = sg.get("win", "")
        if win:
            sg["win"] = translate_datamap_path(win)

    return out
