"""Comprehensive placeable-class catalog for the Add-Placement GUI.

Loads ruse_mod_engine/data/placement_classes.json (generated by
archive/ai_unit_tests/claude/build_placement_class_catalog.py from parametres.Classes + the corpus). This is
the FULL universe of units/buildings/planes the game defines — including the ~277 classes no shipped
scenario has ever placed but which are valid to add — so the editor can offer everything, with usage
context ("placed in N scenarios" vs "never placed, but valid").
"""
import json
import os

from ._resources import data_dir
_DATA = str(data_dir() / "placement_classes.json")
_cache = None


def load():
    global _cache
    if _cache is None:
        try:
            with open(_DATA, encoding="utf-8") as f:
                _cache = json.load(f)
        except Exception:
            _cache = {"classes": {}, "by_category": {}}
    return _cache


def categories():
    """{category: count}, e.g. {'unit': 234, 'building': 150, 'plane': 63, 'para': 9, 'depot': 1}."""
    return load().get("by_category", {})


def info_for(name):
    return load().get("classes", {}).get(name)


def search(category=None, placed=None, query="", limit=None):
    """Filtered [(name, info)] sorted by usage desc then name.
      category : restrict to 'unit'/'building'/'plane'/'para'/'depot' (None = any)
      placed   : True = only ever-placed, False = only never-placed-but-valid, None = both
      query    : case-insensitive substring on the class name
    """
    q = (query or "").lower()
    out = []
    for name, info in load().get("classes", {}).items():
        if category and info.get("category") != category:
            continue
        if placed is not None and bool(info.get("ever_placed")) != placed:
            continue
        if q and q not in name.lower():
            continue
        out.append((name, info))
    out.sort(key=lambda kv: (-(kv[1].get("used_count") or 0), kv[0]))
    return out[:limit] if limit else out


def placement_string(name):
    """The PythonClassName string to write for class `name` (observed if ever placed, else the
    importable parametres.Classes path)."""
    info = info_for(name)
    return info.get("placement_string") if info else ("front.parametres.Classes." + name)


def kind_for_category(cat):
    """Map a catalog category to the editor placement KIND used by the schema/creation path."""
    return {"unit": "unit", "para": "unit", "plane": "unit",
            "building": "building", "depot": "depot"}.get(cat, "spawn")
